Main added, tests added
MlynorikAlina/find_palindrome pull request #1
Opened 2020-09-22 05:02 UTC by MlynorikAlina

2020-09-22 18:26 UTC, VeronikaYastr requested changes

2020-09-22 18:26 UTC, VeronikaYastr commented on src/main/com/bsu/Main.java
> +            if (maxPalindrome.length() == 0) System.out.println("No palindrome word in the text");
Наверное, здесь if-else должно быть. А то у тебя обе строки выведутся, если length = 0

2020-09-22 18:26 UTC, VeronikaYastr commented on src/main/com/bsu/Main.java
> +        try (Scanner scanner = new Scanner((System.in))) {
А зачем тут двойные скобочки в конструкторе?

2020-09-22 18:26 UTC, VeronikaYastr commented on src/main/com/bsu/Main.java
> +        String tempWord, maxPalindrome = "";
Тебе же вроде не нужно всю строку выводить и запоминать, какой был порядок слов и какие знаки между ними.

Почему нельзя просто разбить на слова через str.split(' ,.') и не пройтись по полученному массиву слов, выбирая палиндром и максимальный по длине?

2020-09-22 18:26 UTC, VeronikaYastr commented on src/test/com/bsu/MainTest.java
> +    public void getMaxPalindromeTest() {
Лучше разбить на несколько методов-тестов с конкретными случаями и соответствующими названиями

2020-09-23 14:13 UTC, MlynorikAlina commented on src/main/com/bsu/Main.java
> +        try (Scanner scanner = new Scanner((System.in))) {
Ой, не заметила. Спасибо

2020-09-23 14:48 UTC, MlynorikAlina commented on src/test/com/bsu/MainTest.java
> +    public void getMaxPalindromeTest() {
Спасибо за совет, исправила. Теперь буду делать так.

2020-09-23 14:49 UTC, MlynorikAlina commented on src/main/com/bsu/Main.java
> +        String tempWord, maxPalindrome = "";
Исправила

2020-09-23 14:51 UTC, MlynorikAlina commented on src/main/com/bsu/Main.java
> +            if (maxPalindrome.length() == 0) System.out.println("No palindrome word in the text");
Да, должно быть... Но оно потерялось. Исправила

2020-09-23 18:16 UTC, VeronikaYastr commented on src/main/com/bsu/Main.java
> +        for (String tempWord : input.split("\\.|,| ")) {
Я бы лучше вынесла в переменную результат input.split(). И разве без \\ не работает? Просто split(",. ")?

2020-09-23 19:39 UTC, MlynorikAlina commented on src/main/com/bsu/Main.java
> +        for (String tempWord : input.split("\\.|,| ")) {
Нет, я пробовала, но у меня так не работает( В переменную вынесла.

2020-09-23 20:47 UTC, VeronikaYastr commented on src/main/com/bsu/Main.java
> +        for (String tempWord : input.split("\\.|,| ")) {
Окей, можно мержить  тогда

2020-09-26 15:32 UTC, merged